### ISSUE TITLE
When sharing posts with multiple images, only the first one is forwarded to Discord

### ISSUE THREAD

**Issue by Moon-0xff** [jake-walker/instagram-discord-bridge#10]
I know this is a bug also in Instagram Web so i am under the impression that's not even possible to know which image of the entire post was the shared one.

In that case i find it's better to forward to Discord every image of the post or a link to the post. Instead of only sending the first one.

I would appreciate it quite a lot if dear maintainer or someone else fix this 'bug'.

Thanks in advance.

**Comment by jake-walker** [comment]
Thanks for the issue @Moon-0xff. This sounds like a good feature to add in.

I think both approaches would work. I expect that adding a link to the post would be most straight forward and I’d prefer adding a link over sending all the images. If a post had 8 images, for example, sending all 8 images to discord would spam the chat. What do you think?

I’m happy to work on this, but would you like to give it a shot if you know some JavaScript?

**Comment by Moon-0xff** [comment]
Almost done with it. Sending a PR soon!

**Comment by jake-walker** [comment]
Resolved in #11
